[package]
name = "lilicore"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.72"
dotenv = "0.15.0"
dotenv_codegen = "0.15.0"
git2 = "0.17.2"
ignore = "0.4.20"
jsonwebtoken = "8.3.0"
regex = "1.9.1"
reqwest = { version = "0.11.18", features = ["json"] }
serde = { version = "1.0.177", features = ["derive"] }
serde_json = "1.0.104"
strum = { version = "0.25.0", features = ["strum_macros", "derive"] }
